services:
  - type: web
    name: careercraft-api
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_ENV
        value: production
      - key: CORS_ORIGINS
        value: "*"
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
